### ISSUE TITLE
under 1.8.8 holograms do not load

### ISSUE THREAD

**Issue by batchkrazy** [sainttx/Holograms#1]
on server reboot holograms do not load back up. they still show in the holograms.yml but are not present in listings or visible in server.

**Comment by batchkrazy** [comment]
[10:21:09] [Server thread/ERROR]: Error occurred while enabling Holograms v1.8.8 (Is it up to date?)
java.lang.IllegalArgumentException: Hologram location cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at com.sainttx.holograms.data.Hologram.<init>(Hologram.java:56) ~[?:?]
	at com.sainttx.holograms.HologramManager.load(HologramManager.java:75) ~[?:?]
	at com.sainttx.holograms.HologramPlugin.onEnable(HologramPlugin.java:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.1.8.8.jar:git-Spigot-76236cb-62a2169]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by sainttx** [comment]
Issue fixed in 673d34f6b9a2ec5599cb495f956e32aac5a804f5
