### ISSUE TITLE
Error in paper 1.16.3

### ISSUE THREAD

**Issue by AcruxOk** [sainttx/Holograms#113]
07.10 03:30:33 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-214]
07.10 03:30:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

---------------------------------------------------------

07.10 03:19:05 [Server] ERROR [Holograms] The plugin couldn't create the NMS controller instance and has been disabled. This is likelydue to no supported Hologram implementation for your CraftBukkit/Spigot version.

**Comment by wyatt-herkamp** [comment]
Please use https://github.com/sainttx/Holograms/pull/112
I have added the 1.16.2/1.16.3 support
