### ISSUE TITLE
Hologram not loading after restart (Invalid Chunk)

### ISSUE THREAD

**Issue by jorisguffens** [sainttx/Holograms#36]
After a restart the hologram doesn't get loaded. This happens for all holograms.

Using version 2.5.0-SNAPSHOT

Stacktrace:

```
[20:26:28] [Server thread/WARN]: [Holograms] Failed to spawn Hologram "info"
com.sainttx.holograms.api.exception.HologramEntitySpawnException: Attempted to spawn hologram entity in invalid chunk
	at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:74) ~[?:?]
	at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:40) ~[?:?]
	at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:47) ~[?:?]
	at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:130) ~[?:?]
	at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:119) ~[?:?]
	at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:58) ~[?:?]
	at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [custom.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [custom.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [custom.jar:git-Spigot-fdc1440-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [custom.jar:git-Spigot-fdc1440-880a532]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.getHandle(CraftChunk.java:44) ~[custom.jar:git-Spigot-fdc1440-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.<init>(CraftChunk.java:30) ~[custom.jar:git-Spigot-fdc1440-880a532]
	at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:72) ~[?:?]
```

I think the chunk is not loaded though it is 1 chunk further than the spawn chunk.
Maybe adding a queue to load the hologram once the chunk is loaded will solve this problem.

**Comment by bobbyjo31** [comment]
same issue

**Comment by bobbyjo31** [comment]
how to fix plz
