### ISSUE TITLE
Failed to spawn hologram

### ISSUE THREAD

**Issue by LoceK** [sainttx/Holograms#43]
[04:44:14 WARN]: [Holograms] Failed to spawn Hologram "i"
com.sainttx.holograms.api.exception.HologramEntitySpawnException: Attempted to spawn hologram entity in invalid chunk
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:74) ~[?:?]
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:40) ~[?:?]
        at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:47) ~[?:?]
        at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:130) ~[?:?]
        at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:119) ~[?:?]
        at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:58) ~[?:?]
        at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.getHandle(CraftChunk.java:44) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.<init>(CraftChunk.java:30) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:72) ~[?:?]
        ... 13 more

**Comment by sainttx** [comment]
This is an error unique to 1.8 which I haven't been able to figure out. Since 1.8 is many years old I won't be looking into a fix for this due to deprecated support.
