### ISSUE TITLE
Paperspigot bug

### ISSUE THREAD

**Issue by slvlr** [sainttx/Holograms#45]
Minecraft 1.14.2 paperspigot 65

[16:34:51] [Server thread/WARN]: [Holograms] Task #59 for Holograms v2.7-SNAPSHOT generated an exception
java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class com.sainttx.holograms.nms.v1_14_R1.EntityNameable
    at com.sainttx.holograms.nms.v1_14_R1.EntityNameable.getBukkitEntity(EntityNameable.java:138) ~[?:?]
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:609) ~[patched_1.14.2.jar:git-Paper-65]
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:534) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:951) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:873) ~[patched_1.14.2.jar:git-Paper-65]
    at com.sainttx.holograms.nms.v1_14_R1.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:74) ~[?:?]
    at com.sainttx.holograms.nms.v1_14_R1.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:38) ~[?:?]
    at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:47) ~[?:?]
    at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:130) ~[?:?]
    at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:119) ~[?:?]
    at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:58) ~[?:?]
    at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:49) ~[?:?]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-65]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by MamiyaOtaru** [comment]
bukkitEntity is private now.  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fa71719350d15fd5d5091c4fe45ff2e86a95371c

Citizens2 fixes their problem with the same issue with this commit https://github.com/CitizensDev/Citizens2/commit/3dad7670c7ac079e5373d97495d0d99ecf021a2f#diff-aca6c2183fd1b7f0a9d193e2ffae59f7

If you are going to continue to change bukkitEntity, looks like it's going to require reflection :(
